Qn3_2__3_Newtons:
	python3 src/main.py Qn3_2__3 Newtons > outputs/Qn3_2__3_Newtons.txt

Qn3_2__3_Secant:
	python3 src/main.py Qn3_2__3 Secant > outputs/Qn3_2__3_Secant.txt

Qn3_2__14b:
	python3 src/main.py Qn3_2__14b Newtons > outputs/Qn3_2__14b.txt

Qn3_2__5:
	python3 src/main.py Qn3_2__5 Newtons > outputs/Qn3_2__5.txt

all:
	python3 src/main.py Qn3_2__3 Newtons > outputs/Qn3_2__3_Newtons.txt
	python3 src/main.py Qn3_2__3 Secant > outputs/Qn3_2__3_Secant.txt
	python3 src/main.py Qn3_2__14b Newtons > outputs/Qn3_2__14b.txt
	python3 src/main.py Qn3_2__5 Newtons > outputs/Qn3_2__5.txt
