Qn7_2__1:
	echo "Section 7.2 Qn.1"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__1.py

Qn7_2__2_a_4:
	echo "Section 7.2 Qn.2 (a) n=4"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 4

Qn7_2__2_a_8:
	echo "Section 7.2 Qn.2 (a) n=8"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 8

Qn7_2__2_a_16:
	echo "Section 7.2 Qn.2 (a) n=16"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 16

Qn7_2__2_b_4:
	echo "Section 7.2 Qn.2 (b) n=4"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 4

Qn7_2__2_b_8:
	echo "Section 7.2 Qn.2 (b) n=8"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 8

Qn7_2__2_b_16:
	echo "Section 7.2 Qn.2 (b) n=16"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 16

Qn7_2__2_a:
	echo "Section 7.2 Qn.2 (a) n=4, 8, 16"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 4
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 8
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 16

Qn7_2__2_b:
	echo "Section 7.2 Qn.2 (b) n=4, 8, 16"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 4
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 8
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 16

Qn7_2__2:
	echo "Section 7.2 Qn.2 (a) n=4, 8, 16"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 4
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 8
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py a 16

	echo "Section 7.2 Qn.2 (b) n=4, 8, 16"
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 4
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 8
	python3 /Users/gangameghanath/Downloads/NumericalAnalysisCS514/Integration/Qn7_2__2.py b 16	

